---
- name: Stop the service if running
  systemd:
    state: stopped
    name: "modes3-{{service_name}}"
  become: true
  ignore_errors: yes
- name: Create the root folder containing the binaries
  file: 
    path: /modes3/ 
    state: directory
    owner: root
    group: root
    mode: 0775
  become: true
- name: "Deploy the service distribution"
  unarchive:
    src: "{{playbook_dir}}/../../src/java/components/hu.bme.mit.inf.modes3.components.{{service_name}}/build/distributions/hu.bme.mit.inf.modes3.components.{{service_name}}.tar"
    dest: /modes3
  become: true
- name: Copy the new systemd unit
  copy:
    src: "{{playbook_dir}}/files/modes3-{{service_name}}.service"
    dest: "/etc/systemd/system/modes3-{{service_name}}.service"
    mode: 0644
    force: yes
  become: true
- name: Enable and start the service
  systemd:
    daemon_reload: yes
    enabled: yes
    state: started
    name: "modes3-{{service_name}}"
  become: true